-- ============================================================
-- AFRODITI Studio - recreare tabele Supabase
-- Copiaza TOT acest fisier in Supabase > SQL Editor si apasa Run o singura data.
-- Generat din supabase/migrations/ (20260507 + 20260511 + 20260616).
-- ============================================================

begin;

create table if not exists public.booking_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  guest_name text not null,
  guest_phone text not null,
  accommodation_id text not null,
  guest_count text not null default '',
  adult_count integer not null default 0,
  child_count integer not null default 0,
  check_in date not null,
  check_out date not null,
  whatsapp_url text not null,
  consent_accepted boolean not null default true,
  consent_accepted_at timestamptz not null default timezone('utc', now()),
  consent_policy_version text not null default '2026-05-07-privacy-consent',
  delete_after timestamptz not null default (timezone('utc', now()) + interval '90 days')
);

alter table public.booking_requests
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists guest_count text default '',
  add column if not exists adult_count integer default 0,
  add column if not exists child_count integer default 0,
  add column if not exists consent_accepted boolean default true,
  add column if not exists consent_accepted_at timestamptz default timezone('utc', now()),
  add column if not exists consent_policy_version text default '2026-05-07-privacy-consent',
  add column if not exists delete_after timestamptz default (timezone('utc', now()) + interval '90 days');

update public.booking_requests
set
  created_at = coalesce(created_at, timezone('utc', now())),
  guest_count = coalesce(
    nullif(guest_count, ''),
    trim(
      concat(
        coalesce(adult_count, 0),
        ' adulti',
        case
          when coalesce(child_count, 0) > 0 then concat(' + ', coalesce(child_count, 0), ' copii')
          else ''
        end
      )
    )
  ),
  adult_count = coalesce(adult_count, 0),
  child_count = coalesce(child_count, 0),
  consent_accepted = coalesce(consent_accepted, true),
  consent_accepted_at = coalesce(consent_accepted_at, created_at, timezone('utc', now())),
  consent_policy_version = coalesce(nullif(consent_policy_version, ''), '2026-05-07-privacy-consent'),
  delete_after = coalesce(delete_after, coalesce(created_at, timezone('utc', now())) + interval '90 days')
where
  created_at is null
  or guest_count is null
  or guest_count = ''
  or adult_count is null
  or child_count is null
  or consent_accepted is null
  or consent_accepted_at is null
  or consent_policy_version is null
  or consent_policy_version = ''
  or delete_after is null;

alter table public.booking_requests
  alter column created_at set default timezone('utc', now()),
  alter column created_at set not null,
  alter column guest_count set default '',
  alter column guest_count set not null,
  alter column adult_count set default 0,
  alter column adult_count set not null,
  alter column child_count set default 0,
  alter column child_count set not null,
  alter column consent_accepted set default true,
  alter column consent_accepted set not null,
  alter column consent_accepted_at set default timezone('utc', now()),
  alter column consent_accepted_at set not null,
  alter column consent_policy_version set default '2026-05-07-privacy-consent',
  alter column consent_policy_version set not null,
  alter column delete_after set default (timezone('utc', now()) + interval '90 days'),
  alter column delete_after set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_guest_counts_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_guest_counts_valid
      check (adult_count >= 0 and child_count >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_nights_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_nights_valid
      check (check_out > check_in);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_consent_must_be_true'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_consent_must_be_true
      check (consent_accepted);
  end if;
end
$$;

create index if not exists booking_requests_created_at_idx
  on public.booking_requests (created_at desc);

create index if not exists booking_requests_delete_after_idx
  on public.booking_requests (delete_after);

comment on table public.booking_requests is
  'Cereri de cazare trimise prin formularul site-ului. Retentia operationala recomandata: maximum 90 de zile.';

alter table public.booking_requests enable row level security;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'booking_requests'
  loop
    execute format('drop policy if exists %I on public.booking_requests', existing_policy.policyname);
  end loop;
end
$$;

revoke all on table public.booking_requests from anon, authenticated;
grant select, insert, update, delete on table public.booking_requests to service_role;

do $$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence('public.booking_requests', 'id');

  if sequence_name is not null then
    execute format('revoke all on sequence %s from anon, authenticated', sequence_name);
    execute format('grant usage, select on sequence %s to service_role', sequence_name);
  end if;
end
$$;

create schema if not exists private;

revoke all on schema private from public, anon, authenticated;
grant usage on schema private to postgres, service_role;

create or replace function private.delete_expired_booking_requests()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  deleted_count integer;
begin
  delete from public.booking_requests
  where delete_after <= timezone('utc', now());

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function private.delete_expired_booking_requests() from public, anon, authenticated;
grant execute on function private.delete_expired_booking_requests() to postgres, service_role;

commit;


begin;

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  event_type text not null,
  form_id text not null default 'booking_request',
  ip_hash text not null default '',
  email_hash text,
  user_agent_hash text,
  user_id uuid,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.security_events
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists event_type text,
  add column if not exists form_id text default 'booking_request',
  add column if not exists ip_hash text default '',
  add column if not exists email_hash text,
  add column if not exists user_agent_hash text,
  add column if not exists user_id uuid,
  add column if not exists metadata jsonb default '{}'::jsonb;

update public.security_events
set
  created_at = coalesce(created_at, timezone('utc', now())),
  event_type = coalesce(nullif(event_type, ''), 'invalid_payload'),
  form_id = coalesce(nullif(form_id, ''), 'booking_request'),
  ip_hash = coalesce(ip_hash, ''),
  metadata = coalesce(metadata, '{}'::jsonb)
where
  created_at is null
  or event_type is null
  or event_type = ''
  or form_id is null
  or form_id = ''
  or ip_hash is null
  or metadata is null;

alter table public.security_events
  alter column created_at set not null,
  alter column event_type set not null,
  alter column form_id set not null,
  alter column ip_hash set not null,
  alter column metadata set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.security_events'::regclass
      and conname = 'security_events_event_type_valid'
  ) then
    alter table public.security_events
      add constraint security_events_event_type_valid
      check (
        event_type in (
          'booking_received',
          'captcha_failed',
          'rate_limited',
          'honeypot_triggered',
          'too_fast_submit',
          'invalid_payload',
          'blocked_email_domain',
          'suspicious_user_agent',
          'direct_insert_attempt'
        )
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.security_events'::regclass
      and conname = 'security_events_hash_lengths_valid'
  ) then
    alter table public.security_events
      add constraint security_events_hash_lengths_valid
      check (
        char_length(ip_hash) <= 128
        and char_length(coalesce(email_hash, '')) <= 128
        and char_length(coalesce(user_agent_hash, '')) <= 128
      );
  end if;
end
$$;

create index if not exists security_events_created_at_idx
  on public.security_events (created_at desc);

create index if not exists security_events_form_ip_created_at_idx
  on public.security_events (form_id, ip_hash, created_at desc);

create index if not exists security_events_form_email_created_at_idx
  on public.security_events (form_id, email_hash, created_at desc)
  where email_hash is not null;

create index if not exists security_events_type_created_at_idx
  on public.security_events (event_type, created_at desc);

alter table public.booking_requests
  add column if not exists guest_email text,
  add column if not exists status text not null default 'pending',
  add column if not exists ip_hash text,
  add column if not exists email_hash text,
  add column if not exists phone_hash text,
  add column if not exists user_agent_hash text,
  add column if not exists spam_score integer not null default 0,
  add column if not exists security_flags text[] not null default '{}'::text[],
  add column if not exists request_source text not null default 'website_booking_form';

update public.booking_requests
set
  status = coalesce(nullif(status, ''), 'pending'),
  adult_count = greatest(coalesce(adult_count, 1), 1),
  child_count = greatest(coalesce(child_count, 0), 0),
  spam_score = coalesce(spam_score, 0),
  security_flags = coalesce(security_flags, '{}'::text[]),
  request_source = coalesce(nullif(request_source, ''), 'website_booking_form')
where
  status is null
  or status = ''
  or adult_count is null
  or adult_count < 1
  or child_count is null
  or child_count < 0
  or spam_score is null
  or security_flags is null
  or request_source is null
  or request_source = '';

alter table public.booking_requests
  alter column status set default 'pending',
  alter column status set not null,
  alter column spam_score set default 0,
  alter column spam_score set not null,
  alter column security_flags set default '{}'::text[],
  alter column security_flags set not null,
  alter column request_source set default 'website_booking_form',
  alter column request_source set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_status_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_status_valid
      check (status in ('pending', 'approved', 'spam', 'blocked')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_text_lengths_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_text_lengths_valid
      check (
        char_length(guest_name) between 2 and 80
        and char_length(guest_phone) between 7 and 32
        and char_length(coalesce(guest_email, '')) <= 160
        and char_length(accommodation_id) <= 40
        and char_length(guest_count) <= 80
        and char_length(whatsapp_url) <= 2048
        and char_length(consent_policy_version) <= 80
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_security_values_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_security_values_valid
      check (
        spam_score between 0 and 100
        and char_length(coalesce(ip_hash, '')) <= 128
        and char_length(coalesce(email_hash, '')) <= 128
        and char_length(coalesce(phone_hash, '')) <= 128
        and char_length(coalesce(user_agent_hash, '')) <= 128
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_accommodation_id_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_accommodation_id_valid
      check (accommodation_id in ('studio-double', 'studio-deluxe')) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_guest_counts_bounded'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_guest_counts_bounded
      check (adult_count between 1 and 4 and child_count between 0 and 4) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_nights_bounded'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_nights_bounded
      check (check_out >= check_in + 4 and check_out <= check_in + 60) not valid;
  end if;
end
$$;

create index if not exists booking_requests_email_hash_idx
  on public.booking_requests (email_hash)
  where email_hash is not null;

create index if not exists booking_requests_phone_hash_idx
  on public.booking_requests (phone_hash)
  where phone_hash is not null;

create index if not exists booking_requests_ip_hash_created_at_idx
  on public.booking_requests (ip_hash, created_at desc)
  where ip_hash is not null;

create index if not exists booking_requests_status_created_at_idx
  on public.booking_requests (status, created_at desc);

do $$
declare
  table_record record;
begin
  for table_record in
    select schemaname, tablename
    from pg_tables
    where schemaname = 'public'
  loop
    execute format('alter table %I.%I enable row level security', table_record.schemaname, table_record.tablename);
  end loop;
end
$$;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname, tablename
    from pg_policies
    where schemaname = 'public'
      and tablename in ('booking_requests', 'security_events')
  loop
    execute format('drop policy if exists %I on public.%I', existing_policy.policyname, existing_policy.tablename);
  end loop;
end
$$;

revoke all on table public.booking_requests from anon, authenticated;
revoke all on table public.security_events from anon, authenticated;
grant select, insert, update, delete on table public.booking_requests to service_role;
grant select, insert, update, delete on table public.security_events to service_role;

do $$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence('public.security_events', 'id');
  if sequence_name is not null then
    execute format('revoke all on sequence %s from anon, authenticated', sequence_name);
    execute format('grant usage, select on sequence %s to service_role', sequence_name);
  end if;
end
$$;

comment on table public.security_events is
  'Evenimente server-side pentru formulare publice. IP, email, telefon si user-agent se pastreaza doar ca hash.';

comment on column public.booking_requests.status is
  'Moderare operationala: pending, approved, spam sau blocked. Cererile publice raman pending implicit.';

commit;


begin;

-- Rezervarile nu mai genereaza un link WhatsApp: confirmarea se trimite automat prin email.
-- Coloana ramane pentru compatibilitate cu inregistrarile vechi, dar devine optionala.
alter table public.booking_requests
  alter column whatsapp_url drop not null;

commit;
