begin;

create table if not exists public.booking_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  guest_name text not null,
  guest_phone text not null,
  accommodation_id text not null,
  guest_count text not null default '',
  adult_count integer not null default 0,
  child_count integer not null default 0,
  check_in date not null,
  check_out date not null,
  whatsapp_url text not null,
  consent_accepted boolean not null default true,
  consent_accepted_at timestamptz not null default timezone('utc', now()),
  consent_policy_version text not null default '2026-05-07-privacy-consent',
  delete_after timestamptz not null default (timezone('utc', now()) + interval '90 days')
);

alter table public.booking_requests
  add column if not exists created_at timestamptz default timezone('utc', now()),
  add column if not exists guest_count text default '',
  add column if not exists adult_count integer default 0,
  add column if not exists child_count integer default 0,
  add column if not exists consent_accepted boolean default true,
  add column if not exists consent_accepted_at timestamptz default timezone('utc', now()),
  add column if not exists consent_policy_version text default '2026-05-07-privacy-consent',
  add column if not exists delete_after timestamptz default (timezone('utc', now()) + interval '90 days');

update public.booking_requests
set
  created_at = coalesce(created_at, timezone('utc', now())),
  guest_count = coalesce(
    nullif(guest_count, ''),
    trim(
      concat(
        coalesce(adult_count, 0),
        ' adulti',
        case
          when coalesce(child_count, 0) > 0 then concat(' + ', coalesce(child_count, 0), ' copii')
          else ''
        end
      )
    )
  ),
  adult_count = coalesce(adult_count, 0),
  child_count = coalesce(child_count, 0),
  consent_accepted = coalesce(consent_accepted, true),
  consent_accepted_at = coalesce(consent_accepted_at, created_at, timezone('utc', now())),
  consent_policy_version = coalesce(nullif(consent_policy_version, ''), '2026-05-07-privacy-consent'),
  delete_after = coalesce(delete_after, coalesce(created_at, timezone('utc', now())) + interval '90 days')
where
  created_at is null
  or guest_count is null
  or guest_count = ''
  or adult_count is null
  or child_count is null
  or consent_accepted is null
  or consent_accepted_at is null
  or consent_policy_version is null
  or consent_policy_version = ''
  or delete_after is null;

alter table public.booking_requests
  alter column created_at set default timezone('utc', now()),
  alter column created_at set not null,
  alter column guest_count set default '',
  alter column guest_count set not null,
  alter column adult_count set default 0,
  alter column adult_count set not null,
  alter column child_count set default 0,
  alter column child_count set not null,
  alter column consent_accepted set default true,
  alter column consent_accepted set not null,
  alter column consent_accepted_at set default timezone('utc', now()),
  alter column consent_accepted_at set not null,
  alter column consent_policy_version set default '2026-05-07-privacy-consent',
  alter column consent_policy_version set not null,
  alter column delete_after set default (timezone('utc', now()) + interval '90 days'),
  alter column delete_after set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_guest_counts_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_guest_counts_valid
      check (adult_count >= 0 and child_count >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_nights_valid'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_nights_valid
      check (check_out > check_in);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.booking_requests'::regclass
      and conname = 'booking_requests_consent_must_be_true'
  ) then
    alter table public.booking_requests
      add constraint booking_requests_consent_must_be_true
      check (consent_accepted);
  end if;
end
$$;

create index if not exists booking_requests_created_at_idx
  on public.booking_requests (created_at desc);

create index if not exists booking_requests_delete_after_idx
  on public.booking_requests (delete_after);

comment on table public.booking_requests is
  'Cereri de cazare trimise prin formularul site-ului. Retentia operationala recomandata: maximum 90 de zile.';

alter table public.booking_requests enable row level security;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'booking_requests'
  loop
    execute format('drop policy if exists %I on public.booking_requests', existing_policy.policyname);
  end loop;
end
$$;

revoke all on table public.booking_requests from anon, authenticated;
grant select, insert, update, delete on table public.booking_requests to service_role;

do $$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence('public.booking_requests', 'id');

  if sequence_name is not null then
    execute format('revoke all on sequence %s from anon, authenticated', sequence_name);
    execute format('grant usage, select on sequence %s to service_role', sequence_name);
  end if;
end
$$;

create schema if not exists private;

revoke all on schema private from public, anon, authenticated;
grant usage on schema private to postgres, service_role;

create or replace function private.delete_expired_booking_requests()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  deleted_count integer;
begin
  delete from public.booking_requests
  where delete_after <= timezone('utc', now());

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function private.delete_expired_booking_requests() from public, anon, authenticated;
grant execute on function private.delete_expired_booking_requests() to postgres, service_role;

commit;
